# =============================================================================
# File: scripts/43_run_topic_v3_validation.R
# Purpose: Blindly classify the 50 manually coded validation records using
#          the frozen topic ontology v3.
#
# This script:
# - makes 50 low-cost API calls using gpt-5-mini;
# - never includes the human codes in the prompt;
# - checkpoints after every record;
# - can be stopped and safely resumed;
# - does not touch the previous full-corpus topic run.
# =============================================================================

source("scripts/00_setup.R")

ontology_file <- here::here(
  "data_raw",
  "topic_ontology_v3.csv"
)

gold_file <- here::here(
  "data_raw",
  "topic_validation_gold_standard_50.csv"
)

output_dir <- here::here(
  "outputs",
  "stage_4_llm",
  "ontology_v3_validation"
)

fs::dir_create(output_dir)

checkpoint_file <- fs::path(
  output_dir,
  "topic_v3_validation_checkpoint.rds"
)

record_output_file <- fs::path(
  output_dir,
  "topic_v3_validation_llm_record.csv"
)

long_output_file <- fs::path(
  output_dir,
  "topic_v3_validation_llm_long.csv"
)

failure_file <- fs::path(
  output_dir,
  "topic_v3_validation_failures.csv"
)

system_prompt_file <- fs::path(
  output_dir,
  "topic_v3_validation_system_prompt.txt"
)

ontology_prompt_file <- fs::path(
  output_dir,
  "topic_v3_validation_ontology_prompt.txt"
)

stopifnot(
  file.exists(ontology_file),
  file.exists(gold_file)
)

api_key <- Sys.getenv("OPENAI_API_KEY")

if (!nzchar(api_key)) {
  stop(
    "OPENAI_API_KEY was not found. Set it before running this script."
  )
}

ontology <- readr::read_csv(
  ontology_file,
  show_col_types = FALSE
)

records <- readr::read_csv(
  gold_file,
  show_col_types = FALSE
) |>
  dplyr::mutate(
    record_id = as.character(record_id),
    title = dplyr::coalesce(
      as.character(title),
      ""
    ),
    abstract = dplyr::coalesce(
      as.character(abstract),
      ""
    )
  ) |>
  # Human codes are deliberately removed before classification.
  dplyr::select(
    sampling_stratum,
    record_sequence,
    record_id,
    title,
    abstract
  )

required_ontology_columns <- c(
  "path_id",
  "hierarchy_path",
  "definition",
  "include_when",
  "exclude_when",
  "examples"
)

missing_ontology_columns <- setdiff(
  required_ontology_columns,
  names(ontology)
)

if (length(missing_ontology_columns) > 0L) {
  stop(
    "Ontology is missing required columns: ",
    paste(
      missing_ontology_columns,
      collapse = ", "
    )
  )
}

if (anyDuplicated(ontology$path_id) > 0L) {
  stop("Duplicate path_id values found in the ontology.")
}

if (anyDuplicated(ontology$hierarchy_path) > 0L) {
  stop("Duplicate hierarchy_path values found in the ontology.")
}

ontology_lines <- ontology |>
  dplyr::transmute(
    prompt_entry = paste0(
      path_id,
      " | ",
      hierarchy_path,
      "\nDefinition: ",
      definition,
      "\nInclude when: ",
      include_when,
      "\nExclude when: ",
      exclude_when,
      "\nExamples: ",
      examples
    )
  ) |>
  dplyr::pull(prompt_entry)

ontology_prompt <- paste(
  ontology_lines,
  collapse = "\n\n"
)

system_prompt <- paste(
  "You are coding titles and abstracts for a systematic map of salmon",
  "aquaculture research using a fixed systems-based ontology.",
  "",
  "TASK",
  "Select every ontology path that represents a substantive research",
  "question, intervention or outcome investigated by the record.",
  "",
  "CORE RULES",
  "1. Code evidence generated by the study, not motivations, background",
  "   statements, contextual examples or issues merely mentioned.",
  "2. An intervention and its principal substantive outcome may both be",
  "   coded when they represent distinct information useful for mapping.",
  "3. Do not code every measurement. Code an outcome only when it is a",
  "   substantive objective or major analytical focus.",
  "4. Use general or multiple-issue codes only when a paper addresses",
  "   several issues broadly and no specific issue dominates.",
  "5. Do not assign both a general code and all of its more specific",
  "   alternatives for the same content.",
  "6. Assign Methods only when development, validation, comparison or",
  "   review of the method is itself the principal contribution.",
  "7. Species and geography are coded separately and must not influence",
  "   topic selection.",
  "8. Cleaner-fish research may be coded as Sea lice control and treatment",
  "   even when the paper studies cleaner-fish welfare, health, behaviour",
  "   or management rather than delousing efficacy.",
  "9. Product food safety and human-health effects of consumption belong",
  "   under Product. Public-health effects caused by farming activities",
  "   belong under People and society.",
  "10. Use only supplied path_id values. Do not create new categories.",
  "",
  "MULTIPLE CODING",
  "Use as many codes as necessary, but no more. Most records should receive",
  "one to three codes. Four or more codes should be unusual and must reflect",
  "clearly distinct substantive questions.",
  "",
  "UNCERTAINTY",
  "Set review_required to true only when the abstract is genuinely ambiguous,",
  "insufficient, or lacks an appropriate supplied code.",
  sep = "\n"
)

readr::write_lines(
  system_prompt,
  system_prompt_file
)

readr::write_lines(
  ontology_prompt,
  ontology_prompt_file
)

response_schema <- list(
  type = "object",
  properties = list(
    assignments = list(
      type = "array",
      items = list(
        type = "object",
        properties = list(
          path_id = list(
            type = "string",
            enum = ontology$path_id
          ),
          confidence = list(
            type = "string",
            enum = c(
              "high",
              "medium",
              "low"
            )
          ),
          evidence = list(
            type = "string"
          )
        ),
        required = c(
          "path_id",
          "confidence",
          "evidence"
        ),
        additionalProperties = FALSE
      )
    ),
    review_required = list(
      type = "boolean"
    ),
    review_reason = list(
      type = c(
        "string",
        "null"
      )
    )
  ),
  required = c(
    "assignments",
    "review_required",
    "review_reason"
  ),
  additionalProperties = FALSE
)

extract_output_text <- function(response) {

  message_items <- response$output[
    vapply(
      response$output,
      function(item) {
        identical(
          item$type,
          "message"
        )
      },
      logical(1)
    )
  ]

  content_items <- unlist(
    lapply(
      message_items,
      function(item) {
        item$content
      }
    ),
    recursive = FALSE
  )

  text_items <- content_items[
    vapply(
      content_items,
      function(item) {
        identical(
          item$type,
          "output_text"
        ) &&
          !is.null(item$text)
      },
      logical(1)
    )
  ]

  if (length(text_items) == 0L) {
    stop(
      "No output_text item was returned."
    )
  }

  text_items[[1]]$text
}

classify_record <- function(
    sampling_stratum,
    record_sequence,
    record_id,
    title,
    abstract
) {

  user_prompt <- paste0(
    "ONTOLOGY\n\n",
    ontology_prompt,
    "\n\nRECORD\n\nTitle: ",
    title,
    "\n\nAbstract: ",
    abstract,
    "\n\nReturn only substantive ontology assignments."
  )

  body <- list(
    model = "gpt-5-mini",
    store = FALSE,
    reasoning = list(
      effort = "low"
    ),
    input = list(
      list(
        role = "system",
        content = list(
          list(
            type = "input_text",
            text = system_prompt
          )
        )
      ),
      list(
        role = "user",
        content = list(
          list(
            type = "input_text",
            text = user_prompt
          )
        )
      )
    ),
    text = list(
      verbosity = "low",
      format = list(
        type = "json_schema",
        name = "topic_v3_validation",
        strict = TRUE,
        schema = response_schema
      )
    )
  )

  parsed <- tryCatch(
    {
      response <- httr2::request(
        "https://api.openai.com/v1/responses"
      ) |>
        httr2::req_auth_bearer_token(
          api_key
        ) |>
        httr2::req_body_json(
          body,
          auto_unbox = TRUE
        ) |>
        httr2::req_timeout(
          180
        ) |>
        httr2::req_retry(
          max_tries = 3,
          backoff = ~ 2^.x
        ) |>
        httr2::req_perform() |>
        httr2::resp_body_json()

      jsonlite::fromJSON(
        extract_output_text(response),
        simplifyVector = FALSE
      )
    },
    error = function(e) {
      structure(
        list(
          message = conditionMessage(e)
        ),
        class = "classification_error"
      )
    }
  )

  if (inherits(
    parsed,
    "classification_error"
  )) {
    return(
      list(
        record = tibble::tibble(
          sampling_stratum = sampling_stratum,
          record_sequence = record_sequence,
          record_id = record_id,
          title = title,
          abstract = abstract,
          assigned_path_ids = NA_character_,
          assigned_paths = NA_character_,
          assignment_count = 0L,
          review_required = TRUE,
          review_reason = NA_character_,
          classification_failed = TRUE,
          classification_error = parsed$message
        ),
        long = tibble::tibble()
      )
    )
  }

  assignment_ids <- vapply(
    parsed$assignments,
    function(x) {
      x$path_id
    },
    character(1)
  )

  # Protect against duplicate IDs in a single response.
  assignment_ids <- unique(
    assignment_ids
  )

  assigned <- ontology |>
    dplyr::filter(
      path_id %in% assignment_ids
    ) |>
    dplyr::arrange(
      match(
        path_id,
        assignment_ids
      )
    )

  assignment_lookup <- parsed$assignments[
    !duplicated(
      vapply(
        parsed$assignments,
        function(x) {
          x$path_id
        },
        character(1)
      )
    )
  ]

  long <- if (
    length(assignment_lookup) == 0L
  ) {
    tibble::tibble()
  } else {
    tibble::tibble(
      sampling_stratum = sampling_stratum,
      record_sequence = record_sequence,
      record_id = record_id,
      title = title,
      abstract = abstract,
      path_id = vapply(
        assignment_lookup,
        function(x) {
          x$path_id
        },
        character(1)
      ),
      confidence = vapply(
        assignment_lookup,
        function(x) {
          x$confidence
        },
        character(1)
      ),
      evidence = vapply(
        assignment_lookup,
        function(x) {
          x$evidence
        },
        character(1)
      )
    ) |>
      dplyr::left_join(
        ontology |>
          dplyr::select(
            path_id,
            hierarchy_path
          ),
        by = "path_id"
      )
  }

  record <- tibble::tibble(
    sampling_stratum = sampling_stratum,
    record_sequence = record_sequence,
    record_id = record_id,
    title = title,
    abstract = abstract,
    assigned_path_ids = if (
      nrow(assigned) == 0L
    ) {
      NA_character_
    } else {
      paste(
        assigned$path_id,
        collapse = "; "
      )
    },
    assigned_paths = if (
      nrow(assigned) == 0L
    ) {
      NA_character_
    } else {
      paste(
        assigned$hierarchy_path,
        collapse = "; "
      )
    },
    assignment_count = nrow(assigned),
    review_required = parsed$review_required,
    review_reason = if (
      is.null(parsed$review_reason)
    ) {
      NA_character_
    } else {
      parsed$review_reason
    },
    classification_failed = FALSE,
    classification_error = NA_character_
  )

  list(
    record = record,
    long = long
  )
}

# -----------------------------------------------------------------------------
# Resume from checkpoint if available
# -----------------------------------------------------------------------------

if (file.exists(checkpoint_file)) {

  checkpoint <- readRDS(
    checkpoint_file
  )

  record_results <- checkpoint$record_results
  long_results <- checkpoint$long_results

  completed_ids <- unique(
    record_results$record_id
  )

  message(
    "Resuming from checkpoint: ",
    length(completed_ids),
    " / ",
    nrow(records),
    " records completed."
  )

} else {

  record_results <- tibble::tibble()
  long_results <- tibble::tibble()
  completed_ids <- character()

  message(
    "Starting new 50-record ontology v3 validation."
  )
}

remaining <- records |>
  dplyr::filter(
    !record_id %in% completed_ids
  )

if (nrow(remaining) == 0L) {
  message(
    "All validation records are already complete."
  )
}

for (i in seq_len(
  nrow(remaining)
)) {

  current <- remaining[i, ]

  message(
    "Classifying ",
    length(completed_ids) + i,
    " / ",
    nrow(records),
    ": record_id ",
    current$record_id
  )

  result <- classify_record(
    sampling_stratum = current$sampling_stratum,
    record_sequence = current$record_sequence,
    record_id = current$record_id,
    title = current$title,
    abstract = current$abstract
  )

  record_results <- dplyr::bind_rows(
    record_results,
    result$record
  )

  long_results <- dplyr::bind_rows(
    long_results,
    result$long
  )

  saveRDS(
    list(
      record_results = record_results,
      long_results = long_results
    ),
    checkpoint_file
  )

  readr::write_csv(
    record_results |>
      dplyr::arrange(
        record_sequence
      ),
    record_output_file,
    na = ""
  )

  readr::write_csv(
    long_results |>
      dplyr::arrange(
        record_sequence,
        path_id
      ),
    long_output_file,
    na = ""
  )

  failures <- record_results |>
    dplyr::filter(
      classification_failed
    )

  readr::write_csv(
    failures,
    failure_file,
    na = ""
  )
}

message("")
message("Ontology v3 LLM validation completed.")
message(
  "Records: ",
  nrow(record_results)
)
message(
  "Failures: ",
  sum(
    record_results$classification_failed
  )
)
message(
  "Record output: ",
  record_output_file
)
message(
  "Long output: ",
  long_output_file
)
message("")
message(
  "Next run: source(\"scripts/44_compare_topic_v3_validation.R\")"
)
